// Preset Poster Templates organized by Categories with Ultra-HD 4K Unsplash Royalty-Free Photos

export interface TemplateCategory {
  id: string
  name: string
  icon?: string
}

export interface PresetTemplate {
  id: string
  categoryId: string
  categoryName: string
  name: string
  description: string
  coverBg: string
  canvasConfig: {
    width: number
    height: number
    bgColor: string
  }
  elements: any[]
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  { id: 'festival', name: '节气节日' },
  { id: 'ecommerce', name: '电商大促' },
  { id: 'guochao', name: '国潮古风' },
  { id: 'recruitment', name: '招聘招募' },
  { id: 'food', name: '餐饮美食' },
]

export const PRESET_TEMPLATES: PresetTemplate[] = [
  // ── 1. 节气节日 (Festival & Solar Terms) ──
  {
    id: 'tpl-fest-qingming',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '清明 · 踏青思故人',
    description: '高清春绿竹风雨意，二十四节气原画大片',
    coverBg: 'linear-gradient(135deg, #15803d 0%, #065f46 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#064e3b',
    },
    elements: [
      {
        id: 'bg-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-overlay',
        type: 'Rect',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        fill: 'rgba(6, 78, 59, 0.55)',
      },
      {
        id: 'border-frame',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'transparent',
        stroke: '#a7f3d0',
        strokeWidth: 2,
        cornerRadius: 20,
      },
      {
        id: 'seal-box',
        type: 'Rect',
        x: 80,
        y: 80,
        width: 60,
        height: 60,
        fill: '#dc2626',
        cornerRadius: 10,
      },
      {
        id: 'seal-text',
        type: 'Text',
        x: 80,
        y: 86,
        width: 60,
        height: 48,
        text: '春',
        fill: '#ffffff',
        fontSize: 34,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'title-qingming',
        type: 'Text',
        x: 160,
        y: 85,
        width: 560,
        height: 60,
        text: '清明 · 踏青思故人',
        fill: '#ecfdf5',
        fontSize: 42,
        props: { fontWeight: '900', letterSpacing: '4px' },
      },
      {
        id: 'poem-sub',
        type: 'Text',
        x: 80,
        y: 165,
        width: 640,
        height: 40,
        text: '万物皆洁齐而清明 · 胜日寻芳泗水滨',
        fill: '#6ee7b7',
        fontSize: 20,
        props: { fontWeight: '600', textAlign: 'center' },
      },
      {
        id: 'hero-photo-nature',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=90&w=1600',
        x: 100,
        y: 230,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#a7f3d0', strokeWidth: 2 },
      },
      {
        id: 'info-box',
        type: 'Rect',
        x: 100,
        y: 740,
        width: 600,
        height: 180,
        fill: 'rgba(6, 78, 59, 0.85)',
        stroke: '#6ee7b7',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'info-text-qingming',
        type: 'Text',
        x: 130,
        y: 770,
        width: 540,
        height: 120,
        text: '🍃 二十四节气特辑 — 感受大自然复苏的勃勃生机\n祈福安康 · 拥抱春日温情\n扫码即可查看节气养生指南与春日踏青路线',
        fill: '#f0fdf4',
        fontSize: 18,
        props: { lineHeight: '1.6' },
      },
      {
        id: 'qr-qingming',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/festival/qingming',
      },
    ],
  },
  {
    id: 'tpl-fest-yuanxiao',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '今日元宵 · 汤圆团圆',
    description: '高清中国红灯笼，喜庆元宵佳节原画海报',
    coverBg: 'linear-gradient(135deg, #991b1b 0%, #7f1d1d 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#7f1d1d',
    },
    elements: [
      {
        id: 'bg-photo-lantern',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1543783232-f72f06aa02bd?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-overlay-red',
        type: 'Rect',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        fill: 'rgba(127, 29, 29, 0.65)',
      },
      {
        id: 'border-gold',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'transparent',
        stroke: '#fef08a',
        strokeWidth: 3,
        cornerRadius: 24,
      },
      {
        id: 'title-yuanxiao',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: '今日元宵 · 团圆喜乐',
        fill: '#fef08a',
        fontSize: 58,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sub-yuanxiao',
        type: 'Text',
        x: 80,
        y: 200,
        width: 640,
        height: 40,
        text: '正月十五吃元宵 · 愿家家团圆户户安康',
        fill: '#ffffff',
        fontSize: 22,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'tangyuan-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fef08a', strokeWidth: 2 },
      },
      {
        id: 'promo-card-yuanxiao',
        type: 'Rect',
        x: 100,
        y: 770,
        width: 600,
        height: 160,
        fill: 'rgba(153, 27, 27, 0.9)',
        stroke: '#fef08a',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'promo-text-yuanxiao',
        type: 'Text',
        x: 130,
        y: 800,
        width: 540,
        height: 100,
        text: '🏮 猜灯谜 · 赏花灯 · 尝特调养生元宵\n凭海报到店即赠【吉祥小团子】一份',
        fill: '#fef08a',
        fontSize: 20,
        props: { fontWeight: '700', textAlign: 'center', lineHeight: '1.6' },
      },
      {
        id: 'qr-yuanxiao',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/festival/yuanxiao',
      },
    ],
  },
  {
    id: 'tpl-fest-midautumn',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '中秋节 · 月圆人团圆',
    description: '金色明月与古典亭台，中秋佳节赏月海报',
    coverBg: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#1e1b4b',
    },
    elements: [
      {
        id: 'bg-photo-moon',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'title-midautumn',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: '中秋佳节 · 月圆人团圆',
        fill: '#fde047',
        fontSize: 56,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'sub-midautumn',
        type: 'Text',
        x: 80,
        y: 200,
        width: 640,
        height: 40,
        text: '但愿人长久 · 千里共婵娟',
        fill: '#e0e7ff',
        fontSize: 22,
        props: { fontWeight: '600', textAlign: 'center' },
      },
      {
        id: 'mooncake-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fde047', strokeWidth: 2 },
      },
      {
        id: 'qr-midautumn',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/midautumn',
      },
    ],
  },
  {
    id: 'tpl-fest-cny',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '新春贺岁 · 龙腾虎跃',
    description: '4K 金致祥龙烫金剪纸，新春大吉海报',
    coverBg: 'linear-gradient(135deg, #7f1d1d 0%, #b91c1c 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#7f1d1d',
    },
    elements: [
      {
        id: 'bg-photo-cny',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1548625361-185121c27c62?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'title-cny',
        type: 'Text',
        x: 80,
        y: 110,
        width: 640,
        height: 90,
        text: '新春贺岁 · 恭贺新禧',
        fill: '#fef08a',
        fontSize: 58,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'sub-cny',
        type: 'Text',
        x: 80,
        y: 210,
        width: 640,
        height: 40,
        text: '龙腾虎跃迎新春 · 阖家安康万事顺意',
        fill: '#ffffff',
        fontSize: 22,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'qr-cny',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/cny',
      },
    ],
  },
  {
    id: 'tpl-fest-children',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: 'Happy Children\'s Day 儿童节',
    description: '高清彩虹天空背景，欢度六一儿童节派对海报',
    coverBg: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0284c7',
    },
    elements: [
      {
        id: 'bg-photo-sky',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'title-children',
        type: 'Text',
        x: 60,
        y: 100,
        width: 680,
        height: 90,
        text: 'Happy Children\'s Day',
        fill: '#facc15',
        fontSize: 52,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'gift-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=90&w=1600',
        x: 100,
        y: 270,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#facc15', strokeWidth: 3 },
      },
      {
        id: 'qr-children',
        type: 'QRCode',
        x: 330,
        y: 960,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/childrens-day',
      },
    ],
  },
  {
    id: 'tpl-fest-valentine',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '情人节 · 浪漫臻爱 LOVE',
    description: '4K 高清玫瑰花瓣与心形框，浪漫情人节海报',
    coverBg: 'linear-gradient(135deg, #881337 0%, #e11d48 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#4c0519',
    },
    elements: [
      {
        id: 'bg-photo-roses',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'title-love',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: 'L O V E · 浪漫情人节',
        fill: '#fecdd3',
        fontSize: 54,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'rose-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#fda4af', strokeWidth: 2 },
      },
      {
        id: 'qr-love',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/valentine',
      },
    ],
  },

  // ── 2. 电商大促 (E-Commerce Megasale) ──
  {
    id: 'tpl-ecom-double11',
    categoryId: 'ecommerce',
    categoryName: '电商大促',
    name: '11.11 全球狂欢大促',
    description: '霓虹夜景大促，爆款美妆礼盒限时 5 折抢购',
    coverBg: 'linear-gradient(135deg, #4c1d95 0%, #831843 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#4c1d95',
    },
    elements: [
      {
        id: 'bg-photo-d11',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'title-d11',
        type: 'Text',
        x: 60,
        y: 90,
        width: 680,
        height: 90,
        text: '11.11 全球狂欢盛典',
        fill: '#f43f5e',
        fontSize: 60,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sub-d11',
        type: 'Text',
        x: 80,
        y: 190,
        width: 640,
        height: 40,
        text: '爆款美妆奢品礼盒 · 5 折封顶限时秒杀',
        fill: '#ffffff',
        fontSize: 24,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'cosmetics-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#f43f5e', strokeWidth: 2 },
      },
      {
        id: 'price-d11',
        type: 'Text',
        x: 100,
        y: 780,
        width: 600,
        height: 80,
        text: '狂欢秒杀价 ￥299.00',
        fill: '#facc15',
        fontSize: 40,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'qr-d11',
        type: 'QRCode',
        x: 330,
        y: 930,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/double11',
      },
    ],
  },
  {
    id: 'tpl-ecom-618',
    categoryId: 'ecommerce',
    categoryName: '电商大促',
    name: '618 狂欢年终大促',
    description: '4K 金致光芒红金大促大片',
    coverBg: 'linear-gradient(135deg, #b91c1c 0%, #7f1d1d 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#7f1d1d',
    },
    elements: [
      {
        id: 'bg-photo-sparkles',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'title-super',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 100,
        text: '618 狂欢大促盛典',
        fill: '#fde047',
        fontSize: 64,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sneaker-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=90&w=1600',
        x: 100,
        y: 280,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fde047', strokeWidth: 2 },
      },
      {
        id: 'qr-code',
        type: 'QRCode',
        x: 330,
        y: 920,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/sale-618',
      },
    ],
  },
  {
    id: 'tpl-ecom-new',
    categoryId: 'ecommerce',
    categoryName: '电商大促',
    name: '新品极简发售海报',
    description: '赛博夜景大片，适合科技与潮牌新品发布',
    coverBg: 'linear-gradient(135deg, #0f172a 0%, #06b6d4 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#030712',
    },
    elements: [
      {
        id: 'bg-cyberpunk-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'txt-new-release',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 80,
        text: 'NEW ARRIVAL 2026',
        fill: '#38bdf8',
        fontSize: 48,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'headphone-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#38bdf8', strokeWidth: 2 },
      },
      {
        id: 'barcode-node',
        type: 'Barcode',
        x: 280,
        y: 960,
        width: 240,
        height: 80,
        text: '690987654321',
      },
    ],
  },

  // ── 3. 国潮古风 (Guochao & Heritage) ──
  {
    id: 'tpl-guochao-tea',
    categoryId: 'guochao',
    categoryName: '国潮古风',
    name: '禅意茶道 · 东方风韵',
    description: '水墨竹影与紫砂茶器，传统茶文化宣传海报',
    coverBg: 'linear-gradient(135deg, #1c1917 0%, #44403c 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#1c1917',
    },
    elements: [
      {
        id: 'bg-photo-tea',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'title-tea',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: '禅茶一味 · 浮生半日',
        fill: '#fef08a',
        fontSize: 54,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'teapot-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fef08a', strokeWidth: 2 },
      },
      {
        id: 'qr-tea',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/teaculture',
      },
    ],
  },
  {
    id: 'tpl-guochao-master',
    categoryId: 'guochao',
    categoryName: '国潮古风',
    name: '国潮崛起 匠心造物',
    description: '4K 古风宫殿原图，朱红典雅金国潮招牌海报',
    coverBg: 'linear-gradient(135deg, #7f1d1d 0%, #991b1b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
    },
    elements: [
      {
        id: 'bg-photo-temple',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'txt-guochao-title',
        type: 'Text',
        x: 80,
        y: 110,
        width: 640,
        height: 100,
        text: '国潮崛起 · 匠心造物',
        fill: '#facc15',
        fontSize: 56,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'porcelain-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=90&w=1600',
        x: 100,
        y: 280,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#facc15', strokeWidth: 2 },
      },
      {
        id: 'qr-guochao',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/guochao',
      },
    ],
  },

  // ── 4. 招聘招募 (Recruitment) ──
  {
    id: 'tpl-recruit-designer',
    categoryId: 'recruitment',
    categoryName: '招聘招募',
    name: 'HIRING DESIGNERS 资深设计师招募',
    description: '寻找视觉魔术师，设计工作室高薪招募',
    coverBg: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#1e1b4b',
    },
    elements: [
      {
        id: 'bg-photo-studio',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'title-designer',
        type: 'Text',
        x: 60,
        y: 90,
        width: 680,
        height: 80,
        text: 'HIRING DESIGNERS',
        fill: '#a855f7',
        fontSize: 52,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'designer-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1542744094-3a31b272c490?q=90&w=1600',
        x: 60,
        y: 200,
        width: 680,
        height: 420,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#a855f7', strokeWidth: 1.5 },
      },
      {
        id: 'qr-designer',
        type: 'QRCode',
        x: 330,
        y: 960,
        width: 140,
        height: 140,
        text: 'mailto:design@studio.com',
      },
    ],
  },
  {
    id: 'tpl-recruit-tech',
    categoryId: 'recruitment',
    categoryName: '招聘招募',
    name: 'WE WANT YOU · 极客招聘',
    description: '4K 科技机房背景，适合互联网/技术团队招募',
    coverBg: 'linear-gradient(135deg, #090d16 0%, #1e293b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#090d16',
    },
    elements: [
      {
        id: 'bg-photo-server',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'txt-recruit-main',
        type: 'Text',
        x: 60,
        y: 90,
        width: 680,
        height: 80,
        text: 'WE WANT YOU 2026',
        fill: '#38bdf8',
        fontSize: 54,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'team-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=90&w=1600',
        x: 60,
        y: 200,
        width: 680,
        height: 420,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'qr-recruit',
        type: 'QRCode',
        x: 330,
        y: 960,
        width: 140,
        height: 140,
        text: 'mailto:hr@techcompany.com',
      },
    ],
  },

  // ── 5. 餐饮美食 (Food & Beverage) ──
  {
    id: 'tpl-food-barbecue',
    categoryId: 'food',
    categoryName: '餐饮美食',
    name: '深夜食堂 · 炭火烧烤精酿夜',
    description: '高清宵夜大牌，炭火串烧与精酿啤酒狂欢',
    coverBg: 'linear-gradient(135deg, #451a03 0%, #78350f 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#451a03',
    },
    elements: [
      {
        id: 'bg-photo-barbecue',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'title-bbq',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: '深夜食堂 · 炭火烧烤季',
        fill: '#fde047',
        fontSize: 56,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'bbq-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=90&w=1600',
        x: 80,
        y: 260,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fde047', strokeWidth: 2 },
      },
      {
        id: 'qr-bbq',
        type: 'QRCode',
        x: 330,
        y: 930,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/bbq',
      },
    ],
  },
  {
    id: 'tpl-food-summer',
    categoryId: 'food',
    categoryName: '餐饮美食',
    name: '夏日冰爽特饮促销',
    description: '4K 热带海滩背景，冷饮买一送一活动海报',
    coverBg: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
    },
    elements: [
      {
        id: 'bg-photo-beach',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'drink-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=90&w=1600',
        x: 80,
        y: 260,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#38bdf8', strokeWidth: 2 },
      },
      {
        id: 'qr-drink',
        type: 'QRCode',
        x: 330,
        y: 920,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/food/summer',
      },
    ],
  },
]
