// Preset Poster Templates organized by Categories with Ultra-HD 4K Photos & Anti-Stretch Cover Mode

export interface TemplateCategory {
  id: string
  name: string
  icon?: string
}

export interface PresetTemplate {
  id: string
  categoryId: string
  categoryName: string
  name: string
  description: string
  coverBg: string
  canvasConfig: {
    width: number
    height: number
    bgColor: string
  }
  elements: any[]
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  { id: 'festival', name: '节气节日' },
  { id: 'ecommerce', name: '电商大促' },
  { id: 'guochao', name: '国潮古风' },
  { id: 'recruitment', name: '招聘招募' },
  { id: 'food', name: '餐饮美食' },
]

export const PRESET_TEMPLATES: PresetTemplate[] = [
  // ── 1. 节气节日 (Festival & Solar Terms) ──
  {
    id: 'tpl-fest-qingming',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '清明 · 踏青思故人',
    description: '高清春绿竹风雨意，二十四节气原画大片',
    coverBg: 'linear-gradient(135deg, #15803d 0%, #065f46 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#064e3b',
    },
    elements: [
      {
        id: 'bg-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-overlay',
        type: 'Rect',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        fill: 'rgba(6, 78, 59, 0.55)',
      },
      {
        id: 'border-frame',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'transparent',
        stroke: '#a7f3d0',
        strokeWidth: 2,
        cornerRadius: 20,
      },
      {
        id: 'seal-box',
        type: 'Rect',
        x: 80,
        y: 80,
        width: 60,
        height: 60,
        fill: '#dc2626',
        cornerRadius: 10,
      },
      {
        id: 'seal-text',
        type: 'Text',
        x: 80,
        y: 86,
        width: 60,
        height: 48,
        text: '春',
        fill: '#ffffff',
        fontSize: 34,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'title-qingming',
        type: 'Text',
        x: 160,
        y: 85,
        width: 560,
        height: 60,
        text: '清明 · 踏青思故人',
        fill: '#ecfdf5',
        fontSize: 42,
        props: { fontWeight: '900', letterSpacing: '4px' },
      },
      {
        id: 'poem-sub',
        type: 'Text',
        x: 80,
        y: 165,
        width: 640,
        height: 40,
        text: '万物皆洁齐而清明 · 胜日寻芳泗水滨',
        fill: '#6ee7b7',
        fontSize: 20,
        props: { fontWeight: '600', textAlign: 'center' },
      },
      {
        id: 'hero-photo-nature',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=90&w=1600',
        x: 100,
        y: 230,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#a7f3d0', strokeWidth: 2 },
      },
      {
        id: 'info-box',
        type: 'Rect',
        x: 100,
        y: 740,
        width: 600,
        height: 180,
        fill: 'rgba(6, 78, 59, 0.85)',
        stroke: '#6ee7b7',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'info-text-qingming',
        type: 'Text',
        x: 130,
        y: 770,
        width: 540,
        height: 120,
        text: '🍃 二十四节气特辑 — 感受大自然复苏的勃勃生机\n祈福安康 · 拥抱春日温情\n扫码即可查看节气养生指南与春日踏青路线',
        fill: '#f0fdf4',
        fontSize: 18,
        props: { lineHeight: '1.6' },
      },
      {
        id: 'qr-qingming',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/festival/qingming',
      },
    ],
  },
  {
    id: 'tpl-fest-yuanxiao',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '今日元宵 · 汤圆团圆',
    description: '高清中国红灯笼，喜庆元宵佳节原画海报',
    coverBg: 'linear-gradient(135deg, #991b1b 0%, #7f1d1d 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#7f1d1d',
    },
    elements: [
      {
        id: 'bg-photo-lantern',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1543783232-f72f06aa02bd?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-overlay-red',
        type: 'Rect',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        fill: 'rgba(127, 29, 29, 0.65)',
      },
      {
        id: 'border-gold',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'transparent',
        stroke: '#fef08a',
        strokeWidth: 3,
        cornerRadius: 24,
      },
      {
        id: 'title-yuanxiao',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: '今日元宵 · 团圆喜乐',
        fill: '#fef08a',
        fontSize: 58,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sub-yuanxiao',
        type: 'Text',
        x: 80,
        y: 200,
        width: 640,
        height: 40,
        text: '正月十五吃元宵 · 愿家家团圆户户安康',
        fill: '#ffffff',
        fontSize: 22,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'tangyuan-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fef08a', strokeWidth: 2 },
      },
      {
        id: 'promo-card-yuanxiao',
        type: 'Rect',
        x: 100,
        y: 770,
        width: 600,
        height: 160,
        fill: 'rgba(153, 27, 27, 0.9)',
        stroke: '#fef08a',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'promo-text-yuanxiao',
        type: 'Text',
        x: 130,
        y: 800,
        width: 540,
        height: 100,
        text: '🏮 猜灯谜 · 赏花灯 · 尝特调养生元宵\n凭海报到店即赠【吉祥小团子】一份',
        fill: '#fef08a',
        fontSize: 20,
        props: { fontWeight: '700', textAlign: 'center', lineHeight: '1.6' },
      },
      {
        id: 'qr-yuanxiao',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/festival/yuanxiao',
      },
    ],
  },
  {
    id: 'tpl-fest-children',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: 'Happy Children\'s Day 儿童节',
    description: '高清彩虹天空背景，欢度六一儿童节派对海报',
    coverBg: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0284c7',
    },
    elements: [
      {
        id: 'bg-photo-sky',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'title-children',
        type: 'Text',
        x: 60,
        y: 100,
        width: 680,
        height: 90,
        text: 'Happy Children\'s Day',
        fill: '#facc15',
        fontSize: 52,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'sub-children',
        type: 'Text',
        text: '童心未泯 · 愿你永保纯真与快乐',
        x: 80,
        y: 200,
        width: 640,
        height: 40,
        fill: '#ffffff',
        fontSize: 24,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'gift-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=90&w=1600',
        x: 100,
        y: 270,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#facc15', strokeWidth: 3 },
      },
      {
        id: 'party-info-box',
        type: 'Rect',
        x: 100,
        y: 780,
        width: 600,
        height: 160,
        fill: 'rgba(255, 255, 255, 0.95)',
        cornerRadius: 20,
      },
      {
        id: 'party-info-text',
        type: 'Text',
        x: 130,
        y: 810,
        width: 540,
        height: 100,
        text: '🎈 61 亲子游园会 & 梦想创意涂鸦大赛\n地点：儿童公园中心广场 | 时间：06.01 10:00',
        fill: '#0284c7',
        fontSize: 20,
        props: { fontWeight: '800', textAlign: 'center', lineHeight: '1.6' },
      },
      {
        id: 'qr-children',
        type: 'QRCode',
        x: 330,
        y: 960,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/childrens-day',
      },
    ],
  },
  {
    id: 'tpl-fest-valentine',
    categoryId: 'festival',
    categoryName: '节气节日',
    name: '情人节 · 浪漫臻爱 LOVE',
    description: '4K 高清玫瑰花瓣与心形框，浪漫情人节海报',
    coverBg: 'linear-gradient(135deg, #881337 0%, #e11d48 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#4c0519',
    },
    elements: [
      {
        id: 'bg-photo-roses',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.5,
        props: { mode: 'cover' },
      },
      {
        id: 'title-love',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 90,
        text: 'L O V E · 浪漫情人节',
        fill: '#fecdd3',
        fontSize: 54,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sub-love',
        type: 'Text',
        text: '爱在日常 · 岁岁年年伴你左右',
        x: 80,
        y: 200,
        width: 640,
        height: 40,
        fill: '#ffffff',
        fontSize: 22,
        props: { fontWeight: '600', textAlign: 'center' },
      },
      {
        id: 'rose-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#fda4af', strokeWidth: 2 },
      },
      {
        id: 'love-card-box',
        type: 'Rect',
        x: 100,
        y: 770,
        width: 600,
        height: 160,
        fill: 'rgba(76, 5, 25, 0.85)',
        stroke: '#fda4af',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'love-card-text',
        type: 'Text',
        x: 130,
        y: 800,
        width: 540,
        height: 100,
        text: '🌹 情人节限定浪漫双人晚餐预订中\n前 50 组预订赠送法国进口红酒与定情鲜花',
        fill: '#ffe4e6',
        fontSize: 20,
        props: { fontWeight: '700', textAlign: 'center', lineHeight: '1.6' },
      },
      {
        id: 'qr-love',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/valentine',
      },
    ],
  },

  // ── 2. 电商大促 (E-Commerce Megasale) ──
  {
    id: 'tpl-ecom-618',
    categoryId: 'ecommerce',
    categoryName: '电商大促',
    name: '618 狂欢年终大促',
    description: '4K 金致光芒红金大促大片',
    coverBg: 'linear-gradient(135deg, #b91c1c 0%, #7f1d1d 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#7f1d1d',
    },
    elements: [
      {
        id: 'bg-photo-sparkles',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'rect-bg-card',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'rgba(127, 29, 29, 0.75)',
        stroke: '#f59e0b',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      {
        id: 'title-super',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 100,
        text: '618 狂欢大促盛典',
        fill: '#fde047',
        fontSize: 64,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '4px' },
      },
      {
        id: 'sub-title',
        type: 'Text',
        x: 80,
        y: 210,
        width: 640,
        height: 50,
        text: '全场爆品 跨店满 300 立减 50',
        fill: '#ffffff',
        fontSize: 26,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'sneaker-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=90&w=1600',
        x: 100,
        y: 280,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#fde047', strokeWidth: 2 },
      },
      {
        id: 'price-tag',
        type: 'Text',
        x: 100,
        y: 800,
        width: 600,
        height: 80,
        text: '到手价 ￥199.00',
        fill: '#facc15',
        fontSize: 42,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'qr-code',
        type: 'QRCode',
        x: 330,
        y: 920,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/sale-618',
      },
    ],
  },
  {
    id: 'tpl-ecom-new',
    categoryId: 'ecommerce',
    categoryName: '电商大促',
    name: '新品极简发售海报',
    description: '赛博夜景大片，适合科技与潮牌新品发布',
    coverBg: 'linear-gradient(135deg, #0f172a 0%, #06b6d4 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#030712',
    },
    elements: [
      {
        id: 'bg-cyberpunk-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'txt-new-release',
        type: 'Text',
        x: 80,
        y: 100,
        width: 640,
        height: 80,
        text: 'NEW ARRIVAL 2026',
        fill: '#38bdf8',
        fontSize: 48,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'txt-new-sub',
        type: 'Text',
        x: 80,
        y: 190,
        width: 640,
        height: 50,
        text: '极光未来概念无线音频单品',
        fill: '#f8fafc',
        fontSize: 32,
        props: { fontWeight: '800', textAlign: 'center' },
      },
      {
        id: 'headphone-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=90&w=1600',
        x: 100,
        y: 260,
        width: 600,
        height: 480,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#38bdf8', strokeWidth: 2 },
      },
      {
        id: 'barcode-node',
        type: 'Barcode',
        x: 280,
        y: 960,
        width: 240,
        height: 80,
        text: '690987654321',
      },
    ],
  },

  // ── 3. 国潮古风 (Guochao & Heritage) ──
  {
    id: 'tpl-guochao-master',
    categoryId: 'guochao',
    categoryName: '国潮古风',
    name: '国潮崛起 匠心造物',
    description: '4K 古风宫殿原图，朱红典雅金国潮招牌海报',
    coverBg: 'linear-gradient(135deg, #7f1d1d 0%, #991b1b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
    },
    elements: [
      {
        id: 'bg-photo-temple',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'rect-border-trad',
        type: 'Rect',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'rgba(15, 23, 42, 0.65)',
        stroke: '#fef08a',
        strokeWidth: 2,
        cornerRadius: 20,
      },
      {
        id: 'txt-guochao-title',
        type: 'Text',
        x: 80,
        y: 110,
        width: 640,
        height: 100,
        text: '国潮崛起 · 匠心造物',
        fill: '#facc15',
        fontSize: 56,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'txt-guochao-sub',
        type: 'Text',
        x: 80,
        y: 220,
        width: 640,
        height: 40,
        text: '东方美学经典重塑 · 传统非遗大展',
        fill: '#ffffff',
        fontSize: 22,
        props: { fontWeight: '700', textAlign: 'center' },
      },
      {
        id: 'porcelain-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=90&w=1600',
        x: 100,
        y: 280,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#facc15', strokeWidth: 2 },
      },
      {
        id: 'qr-guochao',
        type: 'QRCode',
        x: 330,
        y: 950,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/guochao',
      },
    ],
  },

  // ── 4. 招聘招募 (Recruitment) ──
  {
    id: 'tpl-recruit-tech',
    categoryId: 'recruitment',
    categoryName: '招聘招募',
    name: 'WE WANT YOU · 极客招聘',
    description: '4K 科技机房背景，适合互联网/技术团队招募',
    coverBg: 'linear-gradient(135deg, #090d16 0%, #1e293b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#090d16',
    },
    elements: [
      {
        id: 'bg-photo-server',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'txt-recruit-main',
        type: 'Text',
        x: 60,
        y: 90,
        width: 680,
        height: 80,
        text: 'WE WANT YOU 2026',
        fill: '#38bdf8',
        fontSize: 54,
        props: { fontWeight: '900', textAlign: 'center', letterSpacing: '6px' },
      },
      {
        id: 'team-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=90&w=1600',
        x: 60,
        y: 200,
        width: 680,
        height: 420,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'rect-job-box',
        type: 'Rect',
        x: 60,
        y: 650,
        width: 680,
        height: 280,
        fill: 'rgba(30, 41, 59, 0.9)',
        stroke: '#3b82f6',
        strokeWidth: 1.5,
        cornerRadius: 20,
      },
      {
        id: 'txt-job-title',
        type: 'Text',
        x: 90,
        y: 680,
        width: 620,
        height: 40,
        text: '🚀 高级前端工程师 (React / Canvas / Leafer.js)',
        fill: '#60a5fa',
        fontSize: 20,
        props: { fontWeight: '800' },
      },
      {
        id: 'txt-job-perks',
        type: 'Text',
        x: 90,
        y: 730,
        width: 620,
        height: 180,
        text: '💰 薪资待遇：25K - 40K · 16薪 + 顶配 MacBook Pro\n🏢 工作地点：杭州 · 西湖区科技园区\n✨ 福利：全额社保公积金 + 定期体检 + 免费双餐',
        fill: '#cbd5e1',
        fontSize: 16,
        props: { lineHeight: '1.8' },
      },
      {
        id: 'qr-recruit',
        type: 'QRCode',
        x: 330,
        y: 960,
        width: 140,
        height: 140,
        text: 'mailto:hr@techcompany.com',
      },
    ],
  },

  // ── 5. 餐饮美食 (Food & Beverage) ──
  {
    id: 'tpl-food-summer',
    categoryId: 'food',
    categoryName: '餐饮美食',
    name: '夏日冰爽特饮促销',
    description: '4K 热带海滩背景，冷饮买一送一活动海报',
    coverBg: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
    },
    elements: [
      {
        id: 'bg-photo-beach',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=90&w=2000',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'drink-photo-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=90&w=1600',
        x: 80,
        y: 260,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#38bdf8', strokeWidth: 2 },
      },
      {
        id: 'txt-drink-title',
        type: 'Text',
        x: 80,
        y: 110,
        width: 640,
        height: 90,
        text: '夏日冰爽特饮',
        fill: '#38bdf8',
        fontSize: 60,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'price-food-tag',
        type: 'Text',
        x: 100,
        y: 780,
        width: 600,
        height: 80,
        text: '抢购价 ¥ 19.90 (买一送一)',
        fill: '#fbbf24',
        fontSize: 36,
        props: { fontWeight: '900', textAlign: 'center' },
      },
      {
        id: 'qr-drink',
        type: 'QRCode',
        x: 330,
        y: 920,
        width: 140,
        height: 140,
        text: 'https://postercraft.app/food/summer',
      },
    ],
  },
]
