import type { CanvasConfig, EditorNode } from '@/store/useEditorStore'

export interface PresetTemplate {
  id: string
  nameKey: string
  fallbackName: string
  category: 'ecommerce' | 'social' | 'recruitment' | 'business' | 'food'
  thumbnail: string
  canvasConfig: CanvasConfig
  elements: EditorNode[]
}

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'template-guochao',
    nameKey: 'template.guochao',
    fallbackName: '国潮崛起 · 匠心造物展',
    category: 'social',
    thumbnail: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-image-hero',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=80&w=1200',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-mask-shape',
        type: 'Shape',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        fill: 'rgba(15, 23, 42, 0.65)',
      },
      {
        id: 'gold-frame-border',
        type: 'Shape',
        x: 40,
        y: 40,
        width: 720,
        height: 1120,
        fill: 'rgba(0, 0, 0, 0.2)',
        props: { cornerRadius: 20, stroke: '#eab308', strokeWidth: 2 },
      },
      {
        id: 'seal-stamp-box',
        type: 'Shape',
        x: 80,
        y: 80,
        width: 64,
        height: 64,
        fill: '#dc2626',
        props: { cornerRadius: 12, stroke: '#fef08a', strokeWidth: 1.5 },
      },
      {
        id: 'seal-stamp-text',
        type: 'Text',
        text: '国',
        x: 80,
        y: 86,
        width: 64,
        height: 52,
        fill: '#ffffff',
        props: { fontSize: 36, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, textAlign: 'center' },
      },
      {
        id: 'main-title',
        type: 'Text',
        text: '匠心造物 · 东方美学经典重塑',
        x: 160,
        y: 90,
        width: 560,
        height: 50,
        fill: '#fef08a',
        props: { fontSize: 32, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(234, 179, 8, 0.5)', shadowBlur: 15 },
      },
      {
        id: 'sub-title',
        type: 'Text',
        text: '千年遗韵 · 时代新风 — 东方文化器物非遗特展',
        x: 80,
        y: 165,
        width: 640,
        height: 35,
        fill: '#cbd5e1',
        props: { fontSize: 18, fontFamily: 'Inter', textAlign: 'center' },
      },
      {
        id: 'porcelain-showcase-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=800',
        x: 100,
        y: 220,
        width: 600,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#eab308', strokeWidth: 2, shadowColor: 'rgba(234, 179, 8, 0.3)', shadowBlur: 30 },
      },
      {
        id: 'info-card',
        type: 'Shape',
        x: 100,
        y: 730,
        width: 600,
        height: 180,
        fill: 'rgba(15, 23, 42, 0.85)',
        props: { cornerRadius: 20, stroke: '#eab308', strokeWidth: 1.5 },
      },
      {
        id: 'info-text',
        type: 'Text',
        text: '🗓️ 展出时间：2026.09.15 - 10.07 (09:00-18:00)\n📍 展出地点：中国美术馆三层特展厅\n🎫 票务指南：凭预约码免费入场特展区',
        x: 130,
        y: 760,
        width: 540,
        height: 120,
        fill: '#f1f5f9',
        props: { fontSize: 18, fontFamily: 'Inter', lineHeight: '1.6' },
      },
      {
        id: 'qr-code-node',
        type: 'QRCode',
        text: 'https://postercraft.app/guochao/vip',
        x: 330,
        y: 940,
        width: 140,
        height: 140,
      },
      {
        id: 'qr-hint-text',
        type: 'Text',
        text: '扫码预约 VIP 观展通道',
        x: 80,
        y: 1095,
        width: 640,
        height: 30,
        fill: '#94a3b8',
        props: { fontSize: 15, fontFamily: 'Inter', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-summer-drink',
    nameKey: 'template.summerDrink',
    fallbackName: '夏日冰爽特饮促销',
    category: 'food',
    thumbnail: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#0f172a',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-beach-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'bg-art-shape',
        type: 'Shape',
        x: 40,
        y: 50,
        width: 720,
        height: 1100,
        fill: 'rgba(15, 23, 42, 0.65)',
        props: { cornerRadius: 24, stroke: '#38bdf8', strokeWidth: 2 },
      },
      {
        id: 'header-badge',
        type: 'Text',
        text: 'SUMMER COOL DRINKS 2026',
        x: 80,
        y: 100,
        width: 640,
        height: 40,
        fill: '#38bdf8',
        props: { fontSize: 18, fontFamily: 'Outfit', bold: true, letterSpacing: '4px' },
      },
      {
        id: 'main-title',
        type: 'Text',
        text: '夏日冰爽特饮',
        x: 80,
        y: 150,
        width: 640,
        height: 90,
        fill: '#ffffff',
        props: { fontSize: 60, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(56, 189, 248, 0.6)', shadowBlur: 25 },
      },
      {
        id: 'sub-title',
        type: 'Text',
        text: '限时优惠 · 买一送一 (BUY 1 GET 1 FREE)',
        x: 80,
        y: 250,
        width: 640,
        height: 40,
        fill: '#fbbf24',
        props: { fontSize: 22, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'poster-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800',
        x: 80,
        y: 310,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, contain: false, mode: 'cover', stroke: '#38bdf8', strokeWidth: 2, shadowColor: 'rgba(56, 189, 248, 0.3)', shadowBlur: 30 },
      },
      {
        id: 'price-card',
        type: 'Shape',
        x: 80,
        y: 820,
        width: 640,
        height: 160,
        fill: '#1e293b',
        props: { cornerRadius: 20, stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'price-tag',
        type: 'Text',
        text: '抢购价 ¥ 19.9',
        x: 120,
        y: 870,
        width: 340,
        height: 60,
        fill: '#fbbf24',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'qr-code-node',
        type: 'QRCode',
        text: 'https://postercraft.app/promo/summer',
        x: 540,
        y: 840,
        width: 120,
        height: 120,
      },
      {
        id: 'promo-badge-text',
        type: 'Text',
        text: '🔥 爆款推荐',
        x: 640,
        y: 290,
        width: 120,
        height: 36,
        fill: '#f43f5e',
        props: { fontSize: 14, fontFamily: 'Inter', bold: true },
        animation: { type: 'breathe', duration: 1.5 },
      },
    ],
  },
  {
    id: 'template-new-product',
    nameKey: 'template.newProduct',
    fallbackName: '新品极致发售海报',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#030712',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-cyberpunk-city',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=80&w=1200',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.45,
        props: { mode: 'cover' },
      },
      {
        id: 'tech-outer-border',
        type: 'Shape',
        x: 40,
        y: 50,
        width: 720,
        height: 1100,
        fill: 'rgba(3, 7, 18, 0.75)',
        props: { cornerRadius: 24, stroke: '#06bdfc', strokeWidth: 1.5 },
      },
      {
        id: 'product-badge',
        type: 'Text',
        text: 'N E W   R E L E A S E   2 0 2 6',
        x: 80,
        y: 100,
        width: 640,
        height: 30,
        fill: '#06bdfc',
        props: { fontSize: 16, fontFamily: 'Outfit', bold: true, letterSpacing: '4px' },
      },
      {
        id: 'product-title',
        type: 'Text',
        text: '极光未来 · 概念无线音频旗舰',
        x: 80,
        y: 140,
        width: 640,
        height: 80,
        fill: '#ffffff',
        props: { fontSize: 44, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(6, 189, 252, 0.6)', shadowBlur: 25 },
      },
      {
        id: 'product-sub',
        type: 'Text',
        text: '全新系列 · 重磅惊艳上市',
        x: 80,
        y: 230,
        width: 640,
        height: 40,
        fill: '#94a3b8',
        props: { fontSize: 20, fontFamily: 'Inter' },
      },
      {
        id: 'product-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800',
        x: 80,
        y: 290,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#06bdfc', strokeWidth: 2, shadowColor: 'rgba(6, 189, 252, 0.35)', shadowBlur: 35 },
      },
      {
        id: 'spec-card',
        type: 'Shape',
        x: 80,
        y: 800,
        width: 640,
        height: 180,
        fill: '#0f172a',
        props: { cornerRadius: 20, stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'spec-text',
        type: 'Text',
        text: '⚡ 主动智能降噪  |  🎵 Hi-Res 无损发烧音质  |  🔋 50H 极速续航',
        x: 100,
        y: 830,
        width: 600,
        height: 40,
        fill: '#60a5fa',
        props: { fontSize: 16, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'price-text',
        type: 'Text',
        text: '首发尝鲜价 ¥ 1299.00',
        x: 100,
        y: 890,
        width: 360,
        height: 60,
        fill: '#fbbf24',
        props: { fontSize: 32, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'product-barcode',
        type: 'Barcode',
        text: '690123456789',
        x: 480,
        y: 885,
        width: 200,
        height: 70,
      },
      {
        id: 'spin-star-badge',
        type: 'Text',
        text: '✨ 现货预售',
        x: 640,
        y: 265,
        width: 120,
        height: 36,
        fill: '#38bdf8',
        props: { fontSize: 14, fontFamily: 'Inter', bold: true },
        animation: { type: 'breathe', duration: 2 },
      },
    ],
  },
  {
    id: 'template-ecommerce-sale',
    nameKey: 'template.ecommerceSale',
    fallbackName: '618 狂欢大促海报',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=600',
    canvasConfig: {
      width: 1200,
      height: 1200,
      bgColor: '#991b1b',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-bokeh-lights',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1200',
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'main-bg-card',
        type: 'Shape',
        x: 60,
        y: 60,
        width: 1080,
        height: 1080,
        fill: 'rgba(127, 29, 29, 0.8)',
        props: { cornerRadius: 32, stroke: '#fef08a', strokeWidth: 3 },
      },
      {
        id: 'sale-title-1',
        type: 'Text',
        text: '618 狂欢大促 · 尊享盛典',
        x: 120,
        y: 120,
        width: 960,
        height: 120,
        fill: '#fef08a',
        props: { fontSize: 72, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(254, 240, 138, 0.5)', shadowBlur: 20 },
      },
      {
        id: 'prod-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800',
        x: 200,
        y: 280,
        width: 800,
        height: 500,
        props: { cornerRadius: 24, mode: 'cover', stroke: '#fef08a', strokeWidth: 2, shadowColor: 'rgba(0,0,0,0.5)', shadowBlur: 40 },
      },
      {
        id: 'sale-sub',
        type: 'Text',
        text: '全场爆品直降 50% OFF · 领券立减 200 元',
        x: 120,
        y: 820,
        width: 960,
        height: 60,
        fill: '#ffffff',
        props: { fontSize: 32, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'buy-button',
        type: 'Shape',
        x: 360,
        y: 920,
        width: 480,
        height: 100,
        fill: '#facc15',
        props: { cornerRadius: 50 },
      },
      {
        id: 'buy-text',
        type: 'Text',
        text: '立即抢购 ➔',
        x: 360,
        y: 940,
        width: 480,
        height: 60,
        fill: '#7f1d1d',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-party-night',
    nameKey: 'template.partyNight',
    fallbackName: '赛博电音狂欢夜 Party',
    category: 'social',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#09090b',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-stage-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.55,
        props: { mode: 'cover' },
      },
      {
        id: 'party-overlay-card',
        type: 'Shape',
        x: 40,
        y: 50,
        width: 720,
        height: 1100,
        fill: 'rgba(9, 9, 11, 0.7)',
        props: { cornerRadius: 24, stroke: '#f43f5e', strokeWidth: 2 },
      },
      {
        id: 'party-badge',
        type: 'Text',
        text: 'C Y B E R   N I G H T   P A R T Y',
        x: 80,
        y: 100,
        width: 640,
        height: 30,
        fill: '#f43f5e',
        props: { fontSize: 18, fontFamily: 'Outfit', bold: true, letterSpacing: '4px' },
      },
      {
        id: 'party-title',
        type: 'Text',
        text: '赛博电音狂欢夜',
        x: 80,
        y: 145,
        width: 640,
        height: 90,
        fill: '#38bdf8',
        props: { fontSize: 64, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(56, 189, 248, 0.7)', shadowBlur: 30 },
      },
      {
        id: 'party-sub',
        type: 'Text',
        text: '狂热重低音 · 极限光影盛宴 · 知名 DJ 阵容爆燃登场',
        x: 80,
        y: 250,
        width: 640,
        height: 40,
        fill: '#ffffff',
        props: { fontSize: 20, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'info-card-party',
        type: 'Shape',
        x: 80,
        y: 780,
        width: 640,
        height: 200,
        fill: 'rgba(30, 27, 75, 0.85)',
        props: { cornerRadius: 20, stroke: '#818cf8', strokeWidth: 1.5 },
      },
      {
        id: 'party-date-info',
        type: 'Text',
        text: '🗓️ 2026.08.18 | 20:00 - LATE\n📍 莫干山路创意园区 8 号展厅\n🎫 票价：早鸟票 ¥128 / 现场票 ¥168',
        x: 110,
        y: 815,
        width: 400,
        height: 120,
        fill: '#f1f5f9',
        props: { fontSize: 18, fontFamily: 'Inter', lineHeight: '1.6' },
      },
      {
        id: 'qr-party-rsvp',
        type: 'QRCode',
        text: 'https://postercraft.app/party/cyber',
        x: 540,
        y: 815,
        width: 130,
        height: 130,
      },
      {
        id: 'spin-star-party',
        type: 'Text',
        text: '🔥 盛夏狂欢',
        x: 640,
        y: 280,
        width: 120,
        height: 36,
        fill: '#f43f5e',
        props: { fontSize: 14, fontFamily: 'Inter', bold: true },
        animation: { type: 'spin', duration: 8 },
      },
    ],
  },
  {
    id: 'template-tech-recruitment',
    nameKey: 'template.techRecruitment',
    fallbackName: '极客科技招聘海报',
    category: 'recruitment',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#090d16',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-tech-photo',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200',
        x: 0,
        y: 0,
        width: 800,
        height: 1200,
        opacity: 0.35,
        props: { mode: 'cover' },
      },
      {
        id: 'recruit-title',
        type: 'Text',
        text: 'JOIN US 2026',
        x: 60,
        y: 90,
        width: 680,
        height: 80,
        fill: '#38bdf8',
        props: { fontSize: 60, fontFamily: 'Righteous', bold: true, letterSpacing: '6px' },
      },
      {
        id: 'recruit-sub',
        type: 'Text',
        text: '寻找最强前端 / 可视化渲染工程师',
        x: 60,
        y: 180,
        width: 680,
        height: 50,
        fill: '#ffffff',
        props: { fontSize: 32, fontFamily: 'Noto Sans SC', bold: true },
      },
      {
        id: 'team-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=800',
        x: 60,
        y: 250,
        width: 680,
        height: 400,
        props: { cornerRadius: 20, mode: 'cover', stroke: '#38bdf8', strokeWidth: 1.5, shadowColor: 'rgba(56, 189, 248, 0.2)', shadowBlur: 30 },
      },
      {
        id: 'tech-stack-card',
        type: 'Shape',
        x: 60,
        y: 680,
        width: 680,
        height: 280,
        fill: '#1e293b',
        props: { cornerRadius: 20, stroke: '#3b82f6', strokeWidth: 1.5 },
      },
      {
        id: 'job-1',
        type: 'Text',
        text: '🚀 高级前端工程师 (React / Canvas / Leafer.js)',
        x: 90,
        y: 710,
        width: 620,
        height: 40,
        fill: '#60a5fa',
        props: { fontSize: 20, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'job-1-desc',
        type: 'Text',
        text: '💰 薪资待遇：25K - 40K · 16薪 + 顶配 MacBook Pro',
        x: 90,
        y: 760,
        width: 620,
        height: 30,
        fill: '#94a3b8',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'job-location',
        type: 'Text',
        text: '🏢 工作地点：杭州 · 西湖区科技园区',
        x: 90,
        y: 800,
        width: 620,
        height: 30,
        fill: '#cbd5e1',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'qr-apply',
        type: 'QRCode',
        text: 'mailto:hr@techcompany.com',
        x: 330,
        y: 990,
        width: 140,
        height: 140,
      },
      {
        id: 'apply-hint',
        type: 'Text',
        text: '扫码投递简历，直通 CTO 面试',
        x: 60,
        y: 1140,
        width: 680,
        height: 30,
        fill: '#cbd5e1',
        props: { fontSize: 15, fontFamily: 'Noto Sans SC', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-business-card',
    nameKey: 'template.businessCard',
    fallbackName: '高端商务个人名片',
    category: 'business',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600',
    canvasConfig: {
      width: 900,
      height: 540,
      bgColor: '#18181b',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-marble-texture',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200',
        x: 0,
        y: 0,
        width: 900,
        height: 540,
        opacity: 0.4,
        props: { mode: 'cover' },
      },
      {
        id: 'card-border',
        type: 'Shape',
        x: 30,
        y: 30,
        width: 840,
        height: 480,
        fill: 'rgba(24, 24, 27, 0.75)',
        props: { cornerRadius: 20, stroke: '#e4e4e7', strokeWidth: 1.5 },
      },
      {
        id: 'avatar',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600',
        x: 70,
        y: 80,
        width: 180,
        height: 180,
        props: { cornerRadius: 90, mode: 'cover', stroke: '#fbbf24', strokeWidth: 3 },
      },
      {
        id: 'name',
        type: 'Text',
        text: 'Alex Zhang',
        x: 280,
        y: 90,
        width: 400,
        height: 50,
        fill: '#ffffff',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'position',
        type: 'Text',
        text: '高级产品设计总监 / Product Design Director',
        x: 280,
        y: 150,
        width: 500,
        height: 30,
        fill: '#a1a1aa',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'contact-info',
        type: 'Text',
        text: '📱 138-0000-8888  |  ✉️ alex@designcraft.com',
        x: 70,
        y: 300,
        width: 600,
        height: 30,
        fill: '#38bdf8',
        props: { fontSize: 18, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'qr-card',
        type: 'QRCode',
        text: 'https://alexdesign.me',
        x: 710,
        y: 340,
        width: 130,
        height: 130,
      },
    ],
  },
]
