import type { CanvasConfig, EditorNode } from '@/store/useEditorStore'

export interface PresetTemplate {
  id: string
  nameKey: string
  fallbackName: string
  category: 'ecommerce' | 'social' | 'recruitment' | 'business' | 'food'
  thumbnail: string
  canvasConfig: CanvasConfig
  elements: EditorNode[]
}

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'template-summer-drink',
    nameKey: 'template.summerDrink',
    fallbackName: '夏日冰爽特饮促销',
    category: 'food',
    thumbnail: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: {
        type: 'linear',
        from: 'top',
        to: 'bottom',
        stops: ['#0f172a', '#1e1b4b'],
      },
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'bg-art-shape',
        type: 'Shape',
        x: 40,
        y: 60,
        width: 720,
        height: 1080,
        fill: 'rgba(255, 255, 255, 0.03)',
        props: { cornerRadius: 24, stroke: 'rgba(56, 189, 248, 0.3)', strokeWidth: 2 },
      },
      {
        id: 'header-badge',
        type: 'Text',
        text: 'SUMMER COOL DRINKS 2026',
        x: 80,
        y: 110,
        width: 640,
        height: 40,
        fill: '#38bdf8',
        props: { fontSize: 18, fontFamily: 'Outfit', bold: true, letterSpacing: '4px' },
      },
      {
        id: 'main-title',
        type: 'Text',
        text: '夏日冰爽特饮',
        x: 80,
        y: 160,
        width: 640,
        height: 90,
        fill: '#ffffff',
        props: { fontSize: 60, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(56, 189, 248, 0.5)', shadowBlur: 20 },
      },
      {
        id: 'sub-title',
        type: 'Text',
        text: '限时优惠 · 买一送一 (BUY 1 GET 1 FREE)',
        x: 80,
        y: 260,
        width: 640,
        height: 40,
        fill: '#fbbf24',
        props: { fontSize: 22, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'poster-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800',
        x: 80,
        y: 330,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, contain: false, mode: 'cover', shadowColor: 'rgba(56, 189, 248, 0.25)', shadowBlur: 30, shadowY: 10 },
      },
      {
        id: 'price-card',
        type: 'Shape',
        x: 80,
        y: 840,
        width: 640,
        height: 160,
        fill: '#1e293b',
        props: { cornerRadius: 20, stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'price-tag',
        type: 'Text',
        text: '抢购价 ¥ 19.9',
        x: 120,
        y: 890,
        width: 340,
        height: 60,
        fill: '#fbbf24',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'qr-code-node',
        type: 'QRCode',
        text: 'https://postercraft.app/promo/summer',
        x: 540,
        y: 860,
        width: 120,
        height: 120,
      },
      {
        id: 'promo-badge-text',
        type: 'Text',
        text: '🔥 爆款推荐',
        x: 640,
        y: 310,
        width: 120,
        height: 36,
        fill: '#f43f5e',
        props: { fontSize: 14, fontFamily: 'Inter', bold: true },
        animation: { type: 'breathe', duration: 1.5 },
      },
    ],
  },
  {
    id: 'template-new-product',
    nameKey: 'template.newProduct',
    fallbackName: '新品极致发售海报',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#030712',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'tech-outer-border',
        type: 'Shape',
        x: 40,
        y: 50,
        width: 720,
        height: 1100,
        fill: 'rgba(255, 255, 255, 0.02)',
        props: { cornerRadius: 24, stroke: '#06bdfc', strokeWidth: 1.5 },
      },
      {
        id: 'product-badge',
        type: 'Text',
        text: 'N E W   R E L E A S E   2 0 2 6',
        x: 80,
        y: 100,
        width: 640,
        height: 30,
        fill: '#06bdfc',
        props: { fontSize: 16, fontFamily: 'Outfit', bold: true, letterSpacing: '4px' },
      },
      {
        id: 'product-title',
        type: 'Text',
        text: '极光未来 · 概念无线音频旗舰',
        x: 80,
        y: 140,
        width: 640,
        height: 80,
        fill: '#ffffff',
        props: { fontSize: 44, fontFamily: 'ZCOOL QingKe HuangYou', bold: true, shadowColor: 'rgba(6, 189, 252, 0.6)', shadowBlur: 25 },
      },
      {
        id: 'product-sub',
        type: 'Text',
        text: '全新系列 · 重磅惊艳上市',
        x: 80,
        y: 230,
        width: 640,
        height: 40,
        fill: '#94a3b8',
        props: { fontSize: 20, fontFamily: 'Inter' },
      },
      {
        id: 'product-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800',
        x: 80,
        y: 290,
        width: 640,
        height: 480,
        props: { cornerRadius: 20, mode: 'cover', shadowColor: 'rgba(6, 189, 252, 0.3)', shadowBlur: 35, shadowY: 12 },
      },
      {
        id: 'spec-card',
        type: 'Shape',
        x: 80,
        y: 800,
        width: 640,
        height: 180,
        fill: '#0f172a',
        props: { cornerRadius: 20, stroke: '#38bdf8', strokeWidth: 1.5 },
      },
      {
        id: 'spec-text',
        type: 'Text',
        text: '⚡ 主动智能降噪  |  🎵 Hi-Res 无损发烧音质  |  🔋 50H 极速续航',
        x: 100,
        y: 830,
        width: 600,
        height: 40,
        fill: '#60a5fa',
        props: { fontSize: 16, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'price-text',
        type: 'Text',
        text: '首发尝鲜价 ¥ 1299.00',
        x: 100,
        y: 890,
        width: 360,
        height: 60,
        fill: '#fbbf24',
        props: { fontSize: 32, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'product-barcode',
        type: 'Barcode',
        text: '690123456789',
        x: 480,
        y: 885,
        width: 200,
        height: 70,
      },
      {
        id: 'spin-star-badge',
        type: 'Text',
        text: '✨ 现货预售',
        x: 640,
        y: 265,
        width: 120,
        height: 36,
        fill: '#38bdf8',
        props: { fontSize: 14, fontFamily: 'Inter', bold: true },
        animation: { type: 'breathe', duration: 2 },
      },
    ],
  },
  {
    id: 'template-ecommerce-sale',
    nameKey: 'template.ecommerceSale',
    fallbackName: '电商年终狂欢海报',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=600',
    canvasConfig: {
      width: 1200,
      height: 1200,
      bgColor: '#991b1b',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'main-bg-card',
        type: 'Shape',
        x: 60,
        y: 60,
        width: 1080,
        height: 1080,
        fill: '#7f1d1d',
        props: { cornerRadius: 32, stroke: '#fef08a', strokeWidth: 3 },
      },
      {
        id: 'sale-title-1',
        type: 'Text',
        text: '618 狂欢大促 · 尊享盛典',
        x: 120,
        y: 120,
        width: 960,
        height: 120,
        fill: '#fef08a',
        props: { fontSize: 72, fontFamily: 'ZCOOL QingKe HuangYou', bold: true },
      },
      {
        id: 'prod-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800',
        x: 200,
        y: 280,
        width: 800,
        height: 500,
        props: { cornerRadius: 24, mode: 'cover', shadowColor: 'rgba(0,0,0,0.5)', shadowBlur: 40 },
      },
      {
        id: 'sale-sub',
        type: 'Text',
        text: '全场爆品直降 50% OFF · 领券立减 200 元',
        x: 120,
        y: 820,
        width: 960,
        height: 60,
        fill: '#ffffff',
        props: { fontSize: 32, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'buy-button',
        type: 'Shape',
        x: 360,
        y: 920,
        width: 480,
        height: 100,
        fill: '#facc15',
        props: { cornerRadius: 50 },
      },
      {
        id: 'buy-text',
        type: 'Text',
        text: '立即抢购 ➔',
        x: 360,
        y: 940,
        width: 480,
        height: 60,
        fill: '#7f1d1d',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-tech-recruitment',
    nameKey: 'template.techRecruitment',
    fallbackName: '极客科技招聘海报',
    category: 'recruitment',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600',
    canvasConfig: {
      width: 800,
      height: 1200,
      bgColor: '#090d16',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'recruit-title',
        type: 'Text',
        text: 'JOIN US 2026',
        x: 60,
        y: 90,
        width: 680,
        height: 80,
        fill: '#38bdf8',
        props: { fontSize: 60, fontFamily: 'Righteous', bold: true, letterSpacing: '6px' },
      },
      {
        id: 'recruit-sub',
        type: 'Text',
        text: '寻找最强前端 / 可视化渲染工程师',
        x: 60,
        y: 180,
        width: 680,
        height: 50,
        fill: '#ffffff',
        props: { fontSize: 32, fontFamily: 'Noto Sans SC', bold: true },
      },
      {
        id: 'team-hero-img',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=800',
        x: 60,
        y: 250,
        width: 680,
        height: 400,
        props: { cornerRadius: 20, mode: 'cover', shadowColor: 'rgba(56, 189, 248, 0.2)', shadowBlur: 30 },
      },
      {
        id: 'tech-stack-card',
        type: 'Shape',
        x: 60,
        y: 680,
        width: 680,
        height: 280,
        fill: '#1e293b',
        props: { cornerRadius: 20, stroke: '#3b82f6', strokeWidth: 1.5 },
      },
      {
        id: 'job-1',
        type: 'Text',
        text: '🚀 高级前端工程师 (React / Canvas / Leafer.js)',
        x: 90,
        y: 710,
        width: 620,
        height: 40,
        fill: '#60a5fa',
        props: { fontSize: 20, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'job-1-desc',
        type: 'Text',
        text: '💰 薪资待遇：25K - 40K · 16薪 + 顶配 MacBook Pro',
        x: 90,
        y: 760,
        width: 620,
        height: 30,
        fill: '#94a3b8',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'job-location',
        type: 'Text',
        text: '🏢 工作地点：杭州 · 西湖区科技园区',
        x: 90,
        y: 800,
        width: 620,
        height: 30,
        fill: '#cbd5e1',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'qr-apply',
        type: 'QRCode',
        text: 'mailto:hr@techcompany.com',
        x: 330,
        y: 990,
        width: 140,
        height: 140,
      },
      {
        id: 'apply-hint',
        type: 'Text',
        text: '扫码投递简历，直通 CTO 面试',
        x: 60,
        y: 1140,
        width: 680,
        height: 30,
        fill: '#cbd5e1',
        props: { fontSize: 15, fontFamily: 'Noto Sans SC', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-business-card',
    nameKey: 'template.businessCard',
    fallbackName: '高端商务个人名片',
    category: 'business',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600',
    canvasConfig: {
      width: 900,
      height: 540,
      bgColor: '#18181b',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'card-border',
        type: 'Shape',
        x: 30,
        y: 30,
        width: 840,
        height: 480,
        fill: 'rgba(255,255,255,0.02)',
        props: { cornerRadius: 20, stroke: '#e4e4e7', strokeWidth: 1.5 },
      },
      {
        id: 'avatar',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600',
        x: 70,
        y: 80,
        width: 180,
        height: 180,
        props: { cornerRadius: 90, mode: 'cover', stroke: '#fbbf24', strokeWidth: 3 },
      },
      {
        id: 'name',
        type: 'Text',
        text: 'Alex Zhang',
        x: 280,
        y: 90,
        width: 400,
        height: 50,
        fill: '#ffffff',
        props: { fontSize: 36, fontFamily: 'Outfit', bold: true },
      },
      {
        id: 'position',
        type: 'Text',
        text: '高级产品设计总监 / Product Design Director',
        x: 280,
        y: 150,
        width: 500,
        height: 30,
        fill: '#a1a1aa',
        props: { fontSize: 16, fontFamily: 'Inter' },
      },
      {
        id: 'contact-info',
        type: 'Text',
        text: '📱 138-0000-8888  |  ✉️ alex@designcraft.com',
        x: 70,
        y: 300,
        width: 600,
        height: 30,
        fill: '#38bdf8',
        props: { fontSize: 18, fontFamily: 'Inter', bold: true },
      },
      {
        id: 'qr-card',
        type: 'QRCode',
        text: 'https://alexdesign.me',
        x: 710,
        y: 340,
        width: 130,
        height: 130,
      },
    ],
  },
  {
    id: 'template-xiaohongshu-card',
    nameKey: 'template.xiaohongshuCard',
    fallbackName: '小红书潮流干货卡片',
    category: 'social',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600',
    canvasConfig: {
      width: 1080,
      height: 1440,
      bgColor: '#fef2f2',
      scaleMode: 'auto',
    },
    elements: [
      {
        id: 'xhs-card',
        type: 'Shape',
        x: 60,
        y: 60,
        width: 960,
        height: 1320,
        fill: '#ffffff',
        props: { cornerRadius: 36, stroke: '#fca5a5', strokeWidth: 2, shadowColor: 'rgba(239, 68, 68, 0.15)', shadowBlur: 30 },
      },
      {
        id: 'xhs-tag',
        type: 'Text',
        text: '🔥 必看干货 · 前端进阶路线图',
        x: 120,
        y: 120,
        width: 840,
        height: 40,
        fill: '#ef4444',
        props: { fontSize: 24, fontFamily: 'Noto Sans SC', bold: true },
      },
      {
        id: 'xhs-title',
        type: 'Text',
        text: '3分钟掌握 Web 爆款海报编辑器架构设计',
        x: 120,
        y: 180,
        width: 840,
        height: 120,
        fill: '#18181b',
        props: { fontSize: 44, fontFamily: 'Noto Serif SC', bold: true },
      },
      {
        id: 'cover-image',
        type: 'Image',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800',
        x: 120,
        y: 330,
        width: 840,
        height: 600,
        props: { cornerRadius: 24, mode: 'cover' },
      },
      {
        id: 'summary-box',
        type: 'Shape',
        x: 120,
        y: 970,
        width: 840,
        height: 340,
        fill: '#fff1f2',
        props: { cornerRadius: 20 },
      },
      {
        id: 'summary-text',
        type: 'Text',
        text: '✨ 核心要点：\n1. 基于 Canvas / Leafer.js 高效渲染引擎\n2. 多语言 i18n 完整国际化封装\n3. 高清 3x 离屏导出与 30fps 动态视频',
        x: 150,
        y: 1000,
        width: 780,
        height: 280,
        fill: '#881337',
        props: { fontSize: 24, fontFamily: 'LXGW WenKai', lineHeight: '1.6' },
      },
    ],
  },
]
